name: "Release a new version"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "windows-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.15.0'

      - name: "Build & test"
        run: |
            ls
            just test
            just build-release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.exe