name: "Release a new version"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install Rust"
        run: rustup update stable

      - name: "Install cross-compilation tools"
        uses: "taiki-e/setup-cross-toolchain-action@v1"
        with:
          target: "x86_64-pc-windows-gnu"

      - name: "Install just"
        uses: extractions/setup-just@v1
        with:
          just-version: '1.15.0'

      - name: "Build & test"
        run: |
            just test
            just build-release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.exe